[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
policy_engine = "9TRhu4fGB2nPXFGWQUj9sLZdte5bpPucNVcAgLeKXE96"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
init = "yarn run ts-node migrations/initialize.ts"

[test]
startup_wait=6000
